name: Release

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: gradle

      - name: Deploy to GitHub
        id: deploy-to-github
        run: |
          ./gradlew -PforceVersion=${{ github.event.release.tag_name }} publish || echo "deploy failed" >&2
        env:
          DEPLOY_USERNAME: AbdullinAM
          DEPLOY_PASSWORD: ${{ secrets.VORPAL_GITHUB_TOKEN }}
